steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.production', '--build-arg', 'NEXT_PUBLIC_BASE_PATH=${_BASE_PATH}', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/p2p-gear-rental:${_IMAGE_TAG}', '.']
    timeout: 1200s

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/p2p-gear-rental:${_IMAGE_TAG}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'p2p-gear-rental-staging'
    - '--image'
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/p2p-gear-rental:${_IMAGE_TAG}'
    - '--region'
    - 'europe-west2'
    - '--platform'
    - 'managed'
    - '--port'
    - '3000'
    - '--allow-unauthenticated'
    - '--set-secrets'
    - 'DATABASE_URL=stage-database-url:latest'
    - '--set-secrets'
    - 'NEXT_PUBLIC_BASE_URL=stage-next-public-base-url:latest'
    - '--set-secrets'
    - 'NEXT_PUBLIC_SUPABASE_URL=stage-next-public-supabase-url:latest'
    - '--set-secrets'
    - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=stage-next-public-supabase-anon-key:latest'
    - '--set-secrets'
    - 'SUPABASE_SERVICE_ROLE_KEY=stage-supabase-service-role-key:latest'
    - '--set-secrets'
    - 'STRIPE_SECRET_KEY=stage-stripe-secret-key:latest'
    - '--set-secrets'
    - 'STRIPE_WEBHOOK_SECRET=stage-stripe-webhook-secret:latest'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '300'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'

substitutions:
  _LOCATION: 'europe-west2'
  _ARTIFACT_REPO_NAME: 'p2pgear-stage-repo'
  _IMAGE_TAG: 'latest'
  _BASE_PATH: ''

options:
  machineType: 'E2_HIGHCPU_8'
