steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/p2p-gear-rental:$SHORT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/p2p-gear-rental:$SHORT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'p2p-gear-rental'
    - '--image'
    - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/p2p-gear-rental:$SHORT_SHA'
    - '--region'
    - 'europe-west2'
    - '--platform'
    - 'managed'
    - '--port'
    - '3000'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_BASE_URL=$_NEXT_PUBLIC_BASE_URL'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_SUPABASE_URL=$_NEXT_PUBLIC_SUPABASE_URL'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=$_NEXT_PUBLIC_SUPABASE_ANON_KEY'
    - '--set-env-vars'
    - 'REDIS_URL=$_REDIS_URL'
    - '--set-secrets'
    - 'SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest'
    - '--set-secrets'
    - 'STRIPE_SECRET_KEY=stripe-secret-key:latest'
    - '--set-secrets'
    - 'STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '300'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'

substitutions:
  _LOCATION: 'europe-west2'
  _ARTIFACT_REPO_NAME: '$PROJECT_ID-p2p-gear-rental'
  _NEXT_PUBLIC_BASE_URL: 'https://p2p-gear-rental.example.com'
  _NEXT_PUBLIC_SUPABASE_URL: 'https://your-project.supabase.co'
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: 'your-anon-key'
  _REDIS_URL: 'redis://[REDIS_HOST]:[REDIS_PORT]/0'  # Replace with actual Redis connection string after deployment

options:
  machineType: 'E2_HIGHCPU_8'